version: "2.0"

services:
  proxychain:
    image: arthurliang/proxychain:0.1
    ports:
      - "1082:1080/tcp"
      - "8123:8123/tcp"
      - "9001:9001/tcp"
    environment:
      - SSR_SERVER001=az87761-ea-aldm001.eastasia.cloudapp.azure.com
      - SSR_SERVER002=az87761-sea-aldm001.eastasia.cloudapp.azure.com
      - SSR_SERVER003=az87761-je-aldm001.eastasia.cloudapp.azure.com
      - SSR_SERVER004=az87761-wu-aldm001.eastasia.cloudapp.azure.com
      - SSR_SV_PORT=55419
      - SSR_PASS=*P>|cEfsROH.4<@v]M@~
    restart: always

