#
# Dockerfile for ubuntu
#

FROM ubuntu:14.04
MAINTAINER Arthur Liang <arthurnreply@outlook.com>

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
ADD http://mirrors.163.com/.help/sources.list.trusty /etc/apt/sources.list
