#
# Dockerfile for mongors
#
# reference: https://medium.com/lucjuggery/mongodb-replica-set-on-swarm-mode-45d66bc9245
#

FROM mongo:3.4
MAINTAINER Arthur Liang <arthurnreply@outlook.com>

COPY init.sh /tmp/init.sh
CMD /tmp/init.sh
